### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by sajt** [bennycwong/ember-bootstrap-4#1]
`bower                                        ENOTFOUND Package ember-bootstrap-4 not found`
I tryed it:
`bower install git://github.com/bennycwong/ember-bootstrap-4`

**Comment by sajt** [comment]
Oh no!!! The README file is wrong missing the line break.

**Comment by bennycwong** [comment]
@sajt The readme has been updated with more clear install instructions. Thanks for reporting.
